version: '3.8'

services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
    networks:
      - afric-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootPassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootPassword@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - afric-network

  service-discovery:
    build:
      context: ./service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - afric-network

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - service-discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
    networks:
      - afric-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8080"
    depends_on:
      - mongodb
      - config-server
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@Password@mongodb:27017/auth-db?authSource=admin
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
    networks:
      - afric-network

  accounting-service:
    build:
      context: ./accounting-service
    container_name: accounting-service
    ports:
      - "8002:8080"
    depends_on:
      - mongodb
      - config-server
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@Password@mongodb:27017/accounting-db?authSource=admin
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
    networks:
      - afric-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8080"
    depends_on:
      - auth-service
      - accounting-service
      - config-server
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
    networks:
      - afric-network

networks:
  afric-network:
    driver: bridge